const strategiesData = [
  {
    searchObjectKey: "dbaname",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "DBA name",
    extractionPrompt: `Determine if the company uses any other names that are significantly different than its legal name or simple name (simple name is legal name with entity designations removed, such as "Apple" instead of "Apple, Inc.". If so, provide that name. If not, output the company's simple name here.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "legalname",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "legal business name",
    extractionPrompt: `Determine the company's legal name including business entity extension (such as "Inc." or "LLC", etc.), example "Apple, Inc.". It will commonly be found in the google search results where "name' is mentioned in the search terms, or in the company website, especially in the footer. Look for the company name followed by an indicator of entity tuype such as LLC, Inc, LTD, etc. If you find the full company name with extensions in the supplied data then output that value. If not, just output the input legal company name.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "hqaddress",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "headquarters address",
    extractionPrompt: `This is likely to be in Google search results or in a "contact" or similar page in the website content. Search for address patterns: Look for strings matching common formats, such as:
   - U.S.: "\d+ [A-Z][a-z]+ (St|Street|Ave|Avenue|Rd|Road|Blvd|Boulevard|Suite|Unit|Floor) \d*, [A-Z][a-z]+, [A-Z]{2} \d{5}(-\d{4})?" (e.g., "123 Main St, Suite 100, City, ST 12345").
   - International: Include country if present (e.g., "Street Name, City, Postal Code, Country").
   - Often near phone numbers (e.g., "(123) 456-7890"), emails, or maps.
5. If multiple candidates: Select the one most likely HQ (e.g., in Contact/About, not in quotes or examples). If ambiguous, choose the first in a core section.
6. Validate: Ensure it's tied to the company (e.g., not a customer's). If no match, conclude "Not found".
7. Output ONLY the exact address string as it appears (e.g., "123 Main St Suite 100 City, ST 12345"). No explanations, no extra text.`,
    extractAs: "address",
    active: true,
  },
  {
    searchObjectKey: "emails",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "email addresses",
    extractionPrompt: `Determine the email domain and how names are formatted in the company's email address format. List any company email addresses found on the company website or in the google search results`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "phonenumber",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "company phone number",
    extractionPrompt: `Provide the company's main phone number`,
    extractAs: "phone",
    active: true,
  },
  {
    searchObjectKey: "taxid",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "EIN number or tax ID number",
    extractionPrompt: `Provide the company's tax ID or EIN number`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "foundeddate",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "founded date",
    extractionPrompt: `Determine when the company was founded or officially organized/incorporated. This is most likely in the google search results but could be in an "about us" or similar page in the website text. If you can find a full month, day, year, output that. If you can find a year only, output June 30 of the founded year.  If you find month and year only, output the 15th of the month. If you find a full date in the supplied data, mark it as verified. Otherwise do not.`,
    extractAs: "date",
    active: true,
  },
  {
    searchObjectKey: "parentcompany",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "parent company",
    extractionPrompt: `Determine if the company is owned by another larger company and if so, identify that company, output the parent company name or if none is found output "N/A".  Don't mark it as verified.  This information is likely to be in the google search results or in an "about us" or simliar page in the website content.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "stateofincorporation",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "state of incorporation/organization",
    extractionPrompt: `Identify in which state the company is incorporated or organized. This is commonly the same state as the company address, but not always. Many companies from other states incorporate/organize in Delaware, Wyoming and Nevada so be sure to check. Output the known state of incorporation if you find it (it's most likely in the google search results but might be in the footer or in an about us page on the website), and mark it as verified. If you don't find anything then output the state of the company headquarters but leave it unverified.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "employeecount",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "number of employees",
    extractionPrompt: `Determine the number of employees at the company.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "stocksymbol",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "stock symbol",
    extractionPrompt: `Deterimine if the company is publically traded or if it's a private company. If it's public, identify the stock symbol and output that. If it's private, output "Private Company".  If you can't find any information about it being public then assume it's private.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "executives",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "executives",
    extractionPrompt: `identify company  executives and provide their names and job titles. Be sure to include any and all executives that are named on the company website. Also be sure to provide job titles whenever possible.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "founders",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "founders",
    extractionPrompt: `Identify the company's founders and provide their names and iif available, their company job titles.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "investors",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "investors or owners",
    extractionPrompt: `Identify the company's key investors and/or owners and provide their names and if available their company job titles.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "boardmembersadvisors",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "board members or advisors",
    extractionPrompt: `Identify any company board members and/or advisors and provide their names and if available, their job titles.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "team",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "employees",
    extractionPrompt: `List other high-level employees with their titles. Don't duplicate any that are already listed as executives, founders, owners, investors, board members.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "socialpages",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "LinkedIn page or Facebook page or Twitter page",
    extractionPrompt: `Identify the company's social media pages and provide the URLs for each. The best source for these links is the company website footer, use Google search results as a backup.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "totalfunding",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "funding",
    extractionPrompt: `Determine how much money investors have invested in the company (commonly referred to as "funding") and on what dates. If you find no information  output "N/A". If you find only one estimate, output that. If you find multiple, provide a list of each funding event.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "companydescription",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "company description",
    extractionPrompt: `Summarize the information that you can glean about this company and it's products into a 2-3 sentence company overview about what sort of products it offers to what type of customers, start with an industry selection followed by the overview. For example: "Industry: B2B Software" {company name} offers....". Do this last after you've had a chance to read and understand all of the content.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "paymentprocessing",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "payment processing features",
    extractionPrompt: `Determine if this company offers payment processing services to its customers based on google search results and product descriptons on its website.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "capterrapayment",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "site:capterra.com payment processing features",
    extractionPrompt: `Determine if the company offers software that includes payment processing features, list the features.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "payfac",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms:
      "site:https://www.mastercard.com/global/en/business/overview/start-accepting/payment-facilitators.html",
    extractionPrompt: `Is the company listed as a payment facilitator in the Mastercard payment facilitator list?`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "offerdiscover",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "Accept Discover Card",
    extractionPrompt: `if they have a payment processing offer, does it include Discover Card acceptance? Answer "Yes", "No" or "can't be determined"`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "paymentsemployees",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "site:linkedin.com/in and payments",
    extractionPrompt: `List any employees at the company that have the word "payments" in their title or job description together with their job titles and the dates they have held that job title. Only include employees where they are currently in the payments-related role for the company we are researching. Visit the linkedin site for the individual if necessary.`,
    extractAs: "list",
    active: true,
  },
  {
    searchObjectKey: "companyhistory",
    companyIdentification: ["simple_company_name", "legal_company_name", "website_url"],
    searchTerms: "company history",
    extractionPrompt: `Provide an overview of the company history including when it was founded, and by whom, any acquisitions and any other relevant historical information.`,
    extractAs: "simple_text",
    active: true,
  },
  {
    searchObjectKey: "naics",
    companyIdentification: ["none"],
    searchTerms: "NAICS codes",
    extractionPrompt: `Based on the information you have about the company, determine the best fitting 6 digit NAICS code and provide it together with the NAICS description`,
    extractAs: "simple_text",
    active: true,
  },
];

export { strategiesData };
